name: Generate PDF

on:
  push:
    branches: master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install gdebi-core xvfb -y

          curl -LOs https://github.com/wkhtmltopdf/wkhtmltopdf/releases/download/0.12.5/wkhtmltox_0.12.5-1.bionic_amd64.deb
          yes | sudo gdebi wkhtmltox_0.12.5-1.bionic_amd64.deb
        
      - name: Generate PDF
        run: |
          make clean
          make generate

      - name: Commit
        run: |
          # If there's new changes
          ls
          git status
          if [[ -z $(git status -s) ]]; then
            git config --global user.name "Superb Bot"

            git add jeff.pdf
            git commit -m "Publish changes"
           
            git push -u origin master
          fi