name: Generate PDF

on:
  push:
    branches: master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Install wkhtmltopdf
        run: |
          sudo apt-get update && sudo apt-get install wkhtmltopdf -y

      - name: Generate PDF
        run: |
          make clean
          make generate

      - name: Commit
        run: |
          # If there's new changes
          if [[ $(git diff --stat) != '' ]]; then
            git config --global user.name "Superb Bot"

            git add jeff.pdf
            git commit -m "Publish changes"
           
            git push -u origin master
          fi